---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: https://github.com/stephenajulu/ajulusblog/blob/master/gridsome.config.js
  label: Config
- type: document
  path: https://github.com/stephenajulu/ajulusblog/blob/master/package.json
  label: Package.json
- type: directory
  path: https://github.com/stephenajulu/ajulusblog/tree/master/content/posts
  label: Posts
  create: documents
  match: "**/*"
  new_doc_ext: md
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
